# Generated by Django 4.1.7 on 2023-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assessment_t_semester_assessment_t_studentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section_t',
            name='year',
            field=models.CharField(default='2022', max_length=4),
        ),
    ]
